DROP TABLE CUSTOMERS

CREATE TABLE CUSTOMERS(CUSID INT,CUSNAME CHAR(10),CUSLOCATION CHAR(10),PRODUCTCOST INT)

SELECT* FROM CUSTOMERS

INSERT INTO CUSTOMERS VALUES(1,'SPIDER','HYD',25000)
INSERT INTO CUSTOMERS VALUES(2,'PETTER','BANGLOR',32000)
INSERT INTO CUSTOMERS VALUES(3,'JOSHNA','CHENNAI',35000)
INSERT INTO CUSTOMERS VALUES(4,'METR','PUNE',25000)
INSERT INTO CUSTOMERS VALUES(5,'HARI','VIZAG',27000)
INSERT INTO CUSTOMERS VALUES(6,'SWEETY','VIJAYAWADA',33000)
INSERT INTO CUSTOMERS VALUES(7,'SWATHI','PUNE',30000)
INSERT INTO CUSTOMERS VALUES(8,'KRISHNA','HYD',32000)

SELECT CUSID,CUSNAME,PRODUCTCOST,RANK() OVER(ORDER BY PRODUCTCOST ASC) AS RANK FROM CUSTOMERS


SELECT CUSID,CUSNAME,CUSLOCATION,PRODUCTCOST,DENSE_RANK() OVER(ORDER BY PRODUCTCOST DESC) AS DENSE_RANK FROM CUSTOMERS

SELECT CUSID,CUSNAME,CUSLOCATION,PRODUCTCOST,ROW_NUMBER() OVER(ORDER BY PRODUCTCOST DESC) AS ROWNUMBER FROM CUSTOMERS

DROP TABLE H1
CREATE TABLE H1(EMPID INT,EMPNAME VARCHAR(10),LOCATION VARCHAR(10),SALARY MONEY)
SELECT*FROM H1
INSERT INTO H1 VALUES(1,'BBB','HYD',25000)
INSERT INTO H1 VALUES(2,'CCC','PUNE',29000)
INSERT INTO H1 VALUES(3,'DDD','BANGLORE',25000)
INSERT INTO H1 VALUES(4,'FFF','GUNTER',22000)
INSERT INTO H1 VALUES(5,'GGG','VIJAYAWADA',32000)
INSERT INTO H1 VALUES(6,'HHH','VIZAG',22000)

SELECT EMPID,EMPNAME,LOCATION,SALARY, RANK() OVER(ORDER BY SALARY ASC) AS RANK FROM H1

SELECT EMPID,LOCATION,SALARY, DENSE_RANK() OVER(ORDER BY SALARY ASC) AS DENSE_RANK FROM H1

SELECT EMPID,LOCATION,SALARY, ROW_NUMBER() OVER(ORDER BY SALARY ASC) AS ROW_NUMBER FROM H1